[package]
name = "rust-starter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "./server/lib.rs"

[dependencies]
getrandom = { version = "0.2", features = ["js"] }
rand = "0.8.5"
wasm-bindgen = "0.2.78"

[dependencies.web-sys]
version = "0.3.56"
features = ["console"]
