name: Build production zip file
on: push
jobs:
    build:
        name: Build zip file
        concurrency:
            group: production - ${{ github.event.pull_request.number || github.ref }}
            cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: npm install and build
              run: |
                  npm ci
                  npx eslint --max-warnings 0 .
                  npm run build
              env:
                  CI: true
            - name: Create Zip
              run: |
                  zip -r code-block-pro-${{ github.run_number }}.zip . -x $(grep -v '^#' .distignore | tr "\n" " ")
              shell: bash
            - name: Package Zip
              uses: actions/upload-artifact@v3
              with:
                  name: code-block-pro-${{ github.run_number }}.zip
                  retention-days: 5
                  path: |
                      ${{ github.workspace }}/code-block-pro-${{ github.run_number }}.zip
