name: Run Cypress test suite
on:
    push:
    workflow_dispatch:
    schedule:
    # At 08:00 daily
    - cron: "0 8 * * *"
jobs:
    test:
        name: Cypress
        runs-on: ubuntu-latest
        strategy:
            matrix:
                wp-version: [null, '"WordPress/WordPress#master"']
        steps:
            - name: Clone repo
              uses: actions/checkout@v3
            - name: Install server
              run: |
                  npm ci
                  npm install -g @wordpress/env
                  npm run build
                  rm .wp-env.json
            - name: Change WP version
              uses: devops-actions/json-to-file@v1.0.0
              if: ${{ matrix.wp-version }}
              with:
                  filename: 'wp-env.json'
                  json: '{
                    "core": ${{ matrix.wp-version }},
                    "plugins":["."],
                    "mappings": {
                      "wp-content/plugins/prismatic": "https://downloads.wordpress.org/plugin/prismatic.zip"
                    }
                  }'
            - name: Start server
              run: wp-env start --update
            - name: Cypress run
              uses: cypress-io/github-action@v4
              with:
                browser: chrome
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
            - uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-videos
                  path: cypress/videos
