name: Deploy to WordPress.org
on:
    release:
        types: [published]
jobs:
    tag:
        name: Make release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: npm install and build
              run: |
                  npm ci
                  npx eslint --max-warnings 0 .
                  npm run build
              env:
                  CI: true

            - name: WordPress Plugin Deploy
              id: deploy
              uses: 10up/action-wordpress-plugin-deploy@stable
              with:
                  generate-zip: true
              env:
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SLUG: code-block-pro
