name: Deploy to WordPress.org
on:
    release:
        types: [published]
jobs:
    tag:
        name: Make release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: npm install and build
              run: |
                  npm ci
                  npm run build
              env:
                  CI: true

            - name: WordPress Plugin Deploy
              id: deploy
              uses: 10up/action-wordpress-plugin-deploy@stable
              with:
                  generate-zip: true
              env:
                  SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                  SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                  SLUG: rust-starter

            - name: Upload release asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{ steps.deploy.outputs.zip-path }}
                  asset_name: ${{ github.event.repository.name }}.zip
                  asset_content_type: application/zip
